// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Matching$BlossomPlayground = require("./Matching.bs.js");

function App(Props) {
  var name = Props.name;
  return React.createElement("div", undefined, name + " is functioning as desired!");
}

ReactDOMRe.renderToElementWithId(React.createElement(Matching$BlossomPlayground.make, { }), "root");

var make = App;

exports.make = make;
/*  Not a pure module */
